<?php
use App\Form;

$errors = [];
$form = new Form($_POST, $errors);
?>


<header class="my-2 mx-auto col p-2">Realtime Chat App</header>

<section class="container mx-auto p-4 col-md-6 col-lg-5 border border-1">
    <form method="post" enctype="multipart/form-data" class="form-group mx-auto signup">

        <!-- Error validate image -->
        <?php if(!empty($e)): ?>
            <div class="alert alert-danger">
                <?php foreach ( $e as $err): ?>
                    <?= $err . "<br>" ?> 
                <?php endforeach; ?>
            </div>
        <?php endif ?>

        <!-- Error validate input -->
        <?php if(!empty($errors)): ?>
            <div class="alert alert-danger">
                <?php foreach ( $errors as $err): ?>
                    <?= $err . "<br>" ?>
                <?php endforeach; ?>
            </div>
        <?php endif ?>
        <!-- the input fields generated by class Form -->

        <?= $form->input('first_name', 'First name', 'text') ?>
        <?= $form->input('last_name', 'Last name', 'text') ?>
        <?= $form->input('email', 'Email', 'email') ?>
        <?= $form->input('password', 'Password', 'password') ?>
        <?= $form->input('file', 'Image Profile (Max: 2Mo)', 'file') ?>

        <div class="mx-auto bg-black rounded text-center">
            <input class="btn text-white" id="btnSubmit" type="submit" value="Continue to chat">
        </div>
    </form>

    <div>Already to chat?
        <a href="<?= $router->url('login') ?>" class="">Login now</a>
    </div>

</section>