<?php
use App\Form;
use App\Validate;

$errors = [];
$link = $router->url('users');

if ( empty($_POST['first_name']) || empty($_POST['last_name']) || empty($_POST['email']) || empty($_POST['password']) || (empty($_FILES['file']))) 
{
    $errors = ['champs' => 'Les chamsp ne doivent pas être vide'];
}
else {
    $first_name = $_POST['first_name'];
    $last_name = $_POST['last_name'];
    $email = $_POST['email'];
    $password = $_POST['password'];

    // validate the entry data
    $v = new Validate($_POST);

    // validate ok
    if($v->validateSignup()) {
        dump("validate ok");
    }
    // validate not ok
    else {
        $err = $v->getErrors();
        $errors= $v->changeErrorMessage($err);
        if (strpos(json_encode($errors),'Password') !== false) {
            $errors[] = "Password must be between 8 and 20 characters, 1 uppercase, 1 lowercase, 1 number, 1 special character(!@#\$%\^&\*.) ";
        }
    }
}


dump($errors);


$form = new Form($_POST, $errors);
?>

<header class="my-2 mx-auto col p-2">Realtime Chat App</header>

<section class="container mx-auto p-4 col-md-6 col-lg-5 border border-1">
    <form method="post" enctype="multipart/form-data" class="form-group mx-auto signup">

        <!-- Error validate image -->
        <?php if(!empty($e)): ?>
            <div class="alert alert-danger">
                <?php foreach ( $e as $err): ?>
                    <?= $err . "<br>" ?> 
                <?php endforeach; ?>
            </div>
        <?php endif ?>

        <!-- Error validate input -->
        <?php if(!empty($errors)): ?>
            <div class="alert alert-danger">
                <?php foreach ( $errors as $err): ?>
                    <?= $err . "<br>" ?>
                <?php endforeach; ?>
            </div>
        <?php endif ?>

        <!-- the input fields generated by class Form -->
        <?= $form->input('first_name', 'First name', 'text') ?>
        <?= $form->input('last_name', 'Last name', 'text') ?>
        <?= $form->input('email', 'Email', 'email') ?>
        <?= $form->input('password', 'Password', 'password') ?>
        <?= $form->input('file', 'Image Profile (Max: 2Mo)', 'file') ?>

        <div class="mx-auto bg-black rounded text-center">
            <input class="btn text-white" id="btnSubmit" type="submit" value="Continue to chat">
        </div>
    </form>

    <div>Already to chat?
        <a href="<?= $router->url('login') ?>" class="">Login now</a>
    </div>

</section>